### ISSUE TITLE
Add option to make output relative

### ISSUE THREAD

**Issue by paulocoutinhox** [houmain/spright#10]
Hi,

Can you add an option to remove the output folder from output data?

Example:

```
max-width 1024
max-height 1024
power-of-two true
scale 1.0
padding 2,2
allow-rotate true

output "out/tank-texture.png"
description "out/tank-texture.plist"
  template "../cocos2dx.inja"

id "{{source.filename}}"
glob "images/**/*.png"
```

But in final `tank-texture.plist` the tool make:

```
<key>textureFileName</key>
<string>out/tank-texture.png</string>
```

And i want only:

```
<key>textureFileName</key>
<string>tank-texture.png</string>
```

Is it possible?

**Comment by houmain** [comment]
Hi, please try again with the current version and this configuration:

```
max-width 1024
max-height 1024
power-of-two true
scale 1.0
padding 2,2
allow-rotate true

output "tank-texture.png"
description "tank-texture.plist"
  template "../cocos2dx.inja"

id "{{ source.filenameBase }}"
glob "images/**/*.png"
```

The best way to remove it, is to remove the "out/" from the configuration and pass the output directory in the --path parameter. e.g. `spright -p out`. I still plan to add a template function for removing directories from filenames.

The newly added `source.filenameBase` also removes the extension from the generated sprite ids.

**Comment by paulocoutinhox** [comment]
Perfect, it works for me. Thanks.

**Comment by paulocoutinhox** [comment]
My game made with this:
https://paulocoutinho.pages.dev/gamemania/home/
