### ISSUE TITLE
Add options from this tool

### ISSUE THREAD

**Issue by paulocoutinhox** [houmain/spright#11]
Hi,

This tool is what i use for my games:
https://free-tex-packer.com/app/

You can add their options, example:
- Use base64
- Texture format
- Remove file extension
- Prepend folder name
- [...]

Thanks.

**Comment by houmain** [comment]
Hi, thanks for the suggestions,

One can use `id "{{ source.filenameBase }}"` now for easily generating sprite IDs from filenames without the extension,
or `id "{{ source.filenameStem }}"` for also removing the folder names.

I also added a `base64` function to the template functions. It can be added like this in the .inja file:
```
<key>textureData</key>
<string>{{ base64(texture.path + "/" + texture.filename) }}</string>
```

**Comment by paulocoutinhox** [comment]
Your suggestions works for me.

**Comment by paulocoutinhox** [comment]
My game made with this:
https://paulocoutinho.pages.dev/gamemania/home/
