### ISSUE TITLE
Can't create a Phaser 3 spritesheet

### ISSUE THREAD

**Issue by joseasv** [houmain/spright#18]
Hello. When I try to create a sprite sheet, with a configuration almost identical to the first one in the readme, I get this error:

ERROR: [inja.exception.file_error] failed accessing file at 'phaser.inja'

I'm using Manjaro and installed spright with Pamac. (I believe the repo used is this one https://aur.archlinux.org/packages/spright-git).

**Comment by houmain** [comment]
Thanks for reporting! This should work now already when installing from the AUR.
