### ISSUE TITLE
Feature request: "pack grid"

### ISSUE THREAD

**Issue by joeskeen** [houmain/spright#19]
I'd like to pack my sprites without layout optimization, but instead optimize for human-readability and simple configuration in the game engine of my choice. So for the output, I want it to find the largest input frame and output a grid where each animation type (group) is in a row, and the frames go left-to-right along the columns, with the space taken for each frame being identical (not trimmed). So looking kind of like this:
![image](https://github.com/user-attachments/assets/fabec992-c6cf-4db8-852f-be75f6c8529c)

Edit: I'd like to consume exported sprites like this: https://excaliburjs.com/docs/spritesheets#uniform-grid-based-spritesheet

**Comment by joeskeen** [comment]
Nvm, I found what I wanted to accomplish using Libresprite :)

**Comment by houmain** [comment]
Still thank you for the request!
I already had it on my idea/TODO list and will prioritize it higher.
