### ISSUE TITLE
How to use with Cocos2d-X/Axmol?

### ISSUE THREAD

**Issue by paulocoutinhox** [houmain/spright#7]
Hi,

How to use with Cocos2d-X/Axmol?

Thanks.

**Comment by houmain** [comment]
Hi, thank you for your interest in this project!
I created a template, which should work with Cocos2d-X/Axmol:
[cocos2dx.txt](https://github.com/houmain/spright/files/13537332/cocos2dx.txt)

I tested it with the following spright.conf:
```
sheet "sheet"
  output "out/sheet.png"
  description "out/sheet.plist"
    template "cocos2dx.txt"

glob "sprites/*.png"
  id "{{source.filename}}"
```

**Comment by paulocoutinhox** [comment]
Nice, thanks.
